declare module 'lucide-react-native' {
  import { FC } from 'react';
  import { SvgProps } from 'react-native-svg';

  export interface LucideProps extends SvgProps {
    size?: number | string;
    color?: string;
    stroke?: string;
    fill?: string;
    strokeWidth?: number | string;
  }

  export const Activity: FC<LucideProps>;
  export const AlertCircle: FC<LucideProps>;
  export const Banknote: FC<LucideProps>;
  export const BarChart3: FC<LucideProps>;
  export const Briefcase: FC<LucideProps>;
  export const Calendar: FC<LucideProps>;
  export const Check: FC<LucideProps>;
  export const CheckCircle2: FC<LucideProps>;
  export const ChevronDown: FC<LucideProps>;
  export const ChevronLeft: FC<LucideProps>;
  export const ChevronRight: FC<LucideProps>;
  export const ChevronUp: FC<LucideProps>;
  export const Circle: FC<LucideProps>;
  export const ClipboardList: FC<LucideProps>;
  export const Clock: FC<LucideProps>;
  export const Dot: FC<LucideProps>;
  export const Download: FC<LucideProps>;
  export const FileText: FC<LucideProps>;
  export const GripVertical: FC<LucideProps>;
  export const MoreHorizontal: FC<LucideProps>;
  export const PanelLeft: FC<LucideProps>;
  export const Percent: FC<LucideProps>;
  export const Plus: FC<LucideProps>;
  export const Search: FC<LucideProps>;
  export const TrendingUp: FC<LucideProps>;
  export const Users: FC<LucideProps>;
  export const X: FC<LucideProps>;
  export const FileCheck: FC<LucideProps>;
  export const CreditCard: FC<LucideProps>;
  export const Wallet: FC<LucideProps>;
  export const PieChart: FC<LucideProps>;
  export const BarChart: FC<LucideProps>;
  export const ArrowRight: FC<LucideProps>;
  export const Lock: FC<LucideProps>;
  export const Settings: FC<LucideProps>;
  export const Eye: FC<LucideProps>;
  export const EyeOff: FC<LucideProps>;
  export const Bell: FC<LucideProps>;
  export const Home: FC<LucideProps>;
  export const LogOut: FC<LucideProps>;
  export const User: FC<LucideProps>;
  export const MapPin: FC<LucideProps>;
  export const Phone: FC<LucideProps>;
  export const Mail: FC<LucideProps>;
  export const Info: FC<LucideProps>;
  export const Filter: FC<LucideProps>;
  export const Trash2: FC<LucideProps>;
  export const Edit: FC<LucideProps>;
  export const Copy: FC<LucideProps>;
  export const Share: FC<LucideProps>;
  export const LayoutDashboard: FC<LucideProps>;
  export const Plane: FC<LucideProps>;
  export const CheckSquare: FC<LucideProps>;
  export const Building2: FC<LucideProps>;
  export const UserPlus: FC<LucideProps>;
  export const UserCircle: FC<LucideProps>;
  export const CalendarRange: FC<LucideProps>;
  export const MessageSquare: FC<LucideProps>;
  export const Fingerprint: FC<LucideProps>;
  export const HelpCircle: FC<LucideProps>;
}
