import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';
import { formatDateIST } from './dateTime';

// Company Info - Update these with actual company details
const COMPANY_INFO = {
  name: 'YOUR COMPANY NAME',
  address: 'Address Line 1, City, State - PIN Code',
  website: 'www.yourcompany.com',
  email: 'info@company.com',
  contact: '+91-XXXXXXXXXX',
  year: new Date().getFullYear(),
};

interface ExportOptions {
  format: 'csv' | 'pdf';
  type: 'employee' | 'department';
  department: string;
  employee?: string;
  periodType: 'current' | 'last3' | 'custom';
  fromMonth?: string;
  fromYear?: string;
  toMonth?: string;
  toYear?: string;
  generatedBy: string;
}

interface EmployeeData {
  empId: string;
  name: string;
  department: string;
  role: string;
  attendance: number;
  taskCompletion: number;
  productivity: number | null;
  qualityScore: number | null;
  overallRating: number | null;
  status: string;
}

interface DepartmentData {
  name: string;
  totalEmployees: number;
  avgAttendance: number;
  avgProductivity: number;
  performanceScore: number;
  tasksCompleted: number;
  tasksPending: number;
  status: string;
}

// Helper: Get period label
const getPeriodLabel = (options: ExportOptions): string => {
  if (options.periodType === 'current') {
    return new Date().toLocaleString('default', { month: 'long', year: 'numeric' });
  }
  if (options.periodType === 'last3') {
    return 'Last 3 Months';
  }
  return `${options.fromMonth} ${options.fromYear} - ${options.toMonth} ${options.toYear}`;
};

// Helper: Generate header
const generateHeader = (): string[] => {
  const lines: string[] = [];
  lines.push('═'.repeat(120));
  lines.push(COMPANY_INFO.name.padStart(60 + COMPANY_INFO.name.length / 2).padEnd(120));
  lines.push('═'.repeat(120));
  lines.push('');
  return lines;
};

// Helper: Generate footer with company details
const generateFooterWithDetails = (): string[] => {
  const lines: string[] = [];
  lines.push('');
  lines.push('═'.repeat(120));
  lines.push(`Address: ${COMPANY_INFO.address}`);
  lines.push(`Website: ${COMPANY_INFO.website} | Email: ${COMPANY_INFO.email} | Contact: ${COMPANY_INFO.contact}`);
  lines.push('═'.repeat(120));
  const footerText = `© ${COMPANY_INFO.year} ${COMPANY_INFO.name}. All rights reserved.`;
  lines.push(footerText.padStart(60 + footerText.length / 2).padEnd(120));
  lines.push('═'.repeat(120));
  return lines;
};

// Helper: Generate footer
const generateFooter = (pageNumber: number = 1): string[] => {
  const lines: string[] = [];
  lines.push('');
  lines.push('═'.repeat(120));
  const footerText = `© ${COMPANY_INFO.year} ${COMPANY_INFO.name}. All rights reserved.`;
  const pageText = `Page ${pageNumber}`;
  const totalLength = 120;
  const footerLength = footerText.length;
  const pageLength = pageText.length;
  const spaceBetween = totalLength - footerLength - pageLength - 2;
  lines.push(footerText + ' '.repeat(Math.max(1, spaceBetween)) + pageText);
  lines.push('═'.repeat(120));
  return lines;
};

// CSV Export for Employees
export const generateEmployeeCSV = async (
  employees: EmployeeData[],
  options: ExportOptions
): Promise<void> => {
  try {
    const csvRows: string[] = [];
    const periodLabel = getPeriodLabel(options);
    const exportDate = formatDateIST(new Date());

    // Header Section
    csvRows.push(...generateHeader());
    csvRows.push('');

    // Report Title
    csvRows.push('EMPLOYEE PERFORMANCE REPORT');
    csvRows.push('');

    // Report Metadata
    csvRows.push('Report Details');
    csvRows.push('─'.repeat(120));
    csvRows.push(`Report ID,RPT-${Date.now()}`);
    csvRows.push(`Generated Date,${exportDate}`);
    csvRows.push(`Generated By,${options.generatedBy}`);
    csvRows.push(`Report Period,${periodLabel}`);
    csvRows.push(`Department,${options.department === 'all' ? 'All Departments' : options.department}`);
    csvRows.push(`Total Records,${employees.length}`);
    csvRows.push('');

    // Column Headers
    csvRows.push('Employee Performance Data');
    csvRows.push('─'.repeat(120));
    csvRows.push(
      'Employee ID,Name,Department,Role,Attendance %,Task Completion %,Productivity %,Quality Score %,Overall Rating %,Status'
    );

    // Data Rows
    if (employees.length === 0) {
      csvRows.push('No employee records found for the selected period');
    } else {
      employees.forEach((emp) => {
        const row = [
          emp.empId || '',
          emp.name || '',
          emp.department || '',
          emp.role || '',
          emp.attendance || 0,
          emp.taskCompletion || 0,
          emp.productivity !== null ? emp.productivity : 'N/A',
          emp.qualityScore !== null ? emp.qualityScore : 'N/A',
          emp.overallRating !== null ? emp.overallRating : 'N/A',
          emp.status || 'average',
        ];
        csvRows.push(row.join(','));
      });
    }

    csvRows.push('');

    // Summary Statistics
    if (employees.length > 0) {
      csvRows.push('Summary Statistics');
      csvRows.push('─'.repeat(120));
      const avgAttendance = Math.round(employees.reduce((sum, e) => sum + e.attendance, 0) / employees.length);
      const avgTasks = Math.round(employees.reduce((sum, e) => sum + e.taskCompletion, 0) / employees.length);
      csvRows.push(`Total Employees,${employees.length}`);
      csvRows.push(`Average Attendance,${avgAttendance}%`);
      csvRows.push(`Average Task Completion,${avgTasks}%`);

      const prodEmployees = employees.filter((e) => e.productivity !== null);
      if (prodEmployees.length > 0) {
        const avgProd = Math.round(prodEmployees.reduce((sum, e) => sum + (e.productivity || 0), 0) / prodEmployees.length);
        csvRows.push(`Average Productivity,${avgProd}% (${prodEmployees.length} rated)`);
      }

      const qualityEmployees = employees.filter((e) => e.qualityScore !== null);
      if (qualityEmployees.length > 0) {
        const avgQuality = Math.round(qualityEmployees.reduce((sum, e) => sum + (e.qualityScore || 0), 0) / qualityEmployees.length);
        csvRows.push(`Average Quality Score,${avgQuality}% (${qualityEmployees.length} rated)`);
      }

      csvRows.push('');
      csvRows.push('Performance Distribution');
      csvRows.push('─'.repeat(120));
      const excellent = employees.filter((e) => e.status === 'excellent').length;
      const good = employees.filter((e) => e.status === 'good').length;
      const average = employees.filter((e) => e.status === 'average').length;
      const poor = employees.filter((e) => e.status === 'poor').length;

      csvRows.push(`Excellent,${excellent},${Math.round((excellent / employees.length) * 100)}%`);
      csvRows.push(`Good,${good},${Math.round((good / employees.length) * 100)}%`);
      csvRows.push(`Average,${average},${Math.round((average / employees.length) * 100)}%`);
      csvRows.push(`Poor,${poor},${Math.round((poor / employees.length) * 100)}%`);
    }

    csvRows.push('');
    csvRows.push(...generateFooterWithDetails());

    const csvContent = csvRows.join('\n');
    const fileName = `Employee_Report_${options.department}_${new Date().toISOString().split('T')[0]}.csv`;
    const fileUri = (FileSystem as any).documentDirectory + fileName;

    await (FileSystem as any).writeAsStringAsync(fileUri, csvContent, {
      encoding: (FileSystem as any).EncodingType?.UTF8,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/csv',
        dialogTitle: 'Save Employee Performance Report',
        UTI: 'public.comma-separated-values-text',
      });
    } else {
      Alert.alert('Success', `Report saved to: ${fileUri}`);
    }
  } catch (error: any) {
    console.error('CSV Export Failed:', error);
    throw new Error(error.message || 'Failed to export employee report');
  }
};

// PDF Export for Employees (Text-based)
export const generateEmployeePDF = async (
  employees: EmployeeData[],
  options: ExportOptions
): Promise<void> => {
  try {
    const reportLines: string[] = [];
    const periodLabel = getPeriodLabel(options);
    const exportDate = formatDateIST(new Date());

    // Header
    reportLines.push(...generateHeader());
    reportLines.push('');

    // Report Title
    reportLines.push('EMPLOYEE PERFORMANCE REPORT'.padStart(65).padEnd(120));
    reportLines.push('');

    // Report Metadata
    reportLines.push('Report Details');
    reportLines.push('─'.repeat(120));
    reportLines.push(`Report ID: RPT-${Date.now()}`.padEnd(120));
    reportLines.push(`Generated Date: ${exportDate}`.padEnd(120));
    reportLines.push(`Generated By: ${options.generatedBy}`.padEnd(120));
    reportLines.push(`Report Period: ${periodLabel}`.padEnd(120));
    reportLines.push(`Department: ${options.department === 'all' ? 'All Departments' : options.department}`.padEnd(120));
    reportLines.push(`Total Records: ${employees.length}`.padEnd(120));
    reportLines.push('');

    // Table Header
    reportLines.push('Employee Performance Data');
    reportLines.push('─'.repeat(120));
    reportLines.push(
      '| ID    | Name                    | Department    | Role         | Att | Task | Prod | Qual | Overall | Status    |'
    );
    reportLines.push('├' + '─'.repeat(118) + '┤');

    // Table Data
    if (employees.length === 0) {
      reportLines.push('| No employee records found for the selected period'.padEnd(119) + '|');
    } else {
      employees.forEach((emp) => {
        const empId = (emp.empId || '').substring(0, 5).padEnd(5);
        const name = (emp.name || '').substring(0, 23).padEnd(23);
        const dept = (emp.department || '').substring(0, 13).padEnd(13);
        const role = (emp.role || '').substring(0, 12).padEnd(12);
        const att = String(emp.attendance || 0).padStart(3);
        const task = String(emp.taskCompletion || 0).padStart(4);
        const prod = (emp.productivity !== null ? String(emp.productivity) : 'N/A').padStart(4);
        const qual = (emp.qualityScore !== null ? String(emp.qualityScore) : 'N/A').padStart(4);
        const overall = (emp.overallRating !== null ? String(emp.overallRating) : 'N/A').padStart(7);
        const status = (emp.status || 'avg').substring(0, 9).padEnd(9);

        reportLines.push(
          `| ${empId} | ${name} | ${dept} | ${role} | ${att}% | ${task}% | ${prod}% | ${qual}% | ${overall}% | ${status} |`
        );
      });
    }

    reportLines.push('└' + '─'.repeat(118) + '┘');
    reportLines.push('');

    // Summary Statistics
    if (employees.length > 0) {
      reportLines.push('Summary Statistics');
      reportLines.push('─'.repeat(120));
      const avgAttendance = Math.round(employees.reduce((sum, e) => sum + e.attendance, 0) / employees.length);
      const avgTasks = Math.round(employees.reduce((sum, e) => sum + e.taskCompletion, 0) / employees.length);

      reportLines.push(`Total Employees Analyzed: ${employees.length}`.padEnd(120));
      reportLines.push(`Average Attendance: ${avgAttendance}%`.padEnd(120));
      reportLines.push(`Average Task Completion: ${avgTasks}%`.padEnd(120));

      const prodEmployees = employees.filter((e) => e.productivity !== null);
      if (prodEmployees.length > 0) {
        const avgProd = Math.round(prodEmployees.reduce((sum, e) => sum + (e.productivity || 0), 0) / prodEmployees.length);
        reportLines.push(`Average Productivity: ${avgProd}% (${prodEmployees.length} rated)`.padEnd(120));
      }

      const qualityEmployees = employees.filter((e) => e.qualityScore !== null);
      if (qualityEmployees.length > 0) {
        const avgQuality = Math.round(qualityEmployees.reduce((sum, e) => sum + (e.qualityScore || 0), 0) / qualityEmployees.length);
        reportLines.push(`Average Quality Score: ${avgQuality}% (${qualityEmployees.length} rated)`.padEnd(120));
      }

      reportLines.push('');
      reportLines.push('Performance Distribution');
      reportLines.push('─'.repeat(120));

      const excellent = employees.filter((e) => e.status === 'excellent').length;
      const good = employees.filter((e) => e.status === 'good').length;
      const average = employees.filter((e) => e.status === 'average').length;
      const poor = employees.filter((e) => e.status === 'poor').length;

      reportLines.push(`Excellent: ${excellent} (${Math.round((excellent / employees.length) * 100)}%)`.padEnd(120));
      reportLines.push(`Good: ${good} (${Math.round((good / employees.length) * 100)}%)`.padEnd(120));
      reportLines.push(`Average: ${average} (${Math.round((average / employees.length) * 100)}%)`.padEnd(120));
      reportLines.push(`Poor: ${poor} (${Math.round((poor / employees.length) * 100)}%)`.padEnd(120));
    }

    reportLines.push('');
    reportLines.push(...generateFooterWithDetails());

    const textContent = reportLines.join('\n');
    const fileName = `Employee_Report_${options.department}_${new Date().toISOString().split('T')[0]}.txt`;
    const fileUri = (FileSystem as any).documentDirectory + fileName;

    await (FileSystem as any).writeAsStringAsync(fileUri, textContent, {
      encoding: (FileSystem as any).EncodingType?.UTF8,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: 'Save Employee Performance Report',
        UTI: 'public.plain-text',
      });
    } else {
      Alert.alert('Success', `Report saved to: ${fileUri}`);
    }
  } catch (error: any) {
    console.error('PDF Export Failed:', error);
    throw new Error(error.message || 'Failed to export employee report');
  }
};

// CSV Export for Departments
export const generateDepartmentCSV = async (
  departments: DepartmentData[],
  options: ExportOptions
): Promise<void> => {
  try {
    const csvRows: string[] = [];
    const periodLabel = getPeriodLabel(options);
    const exportDate = formatDateIST(new Date());

    // Header Section
    csvRows.push(...generateHeader());
    csvRows.push('');

    // Report Title
    csvRows.push('DEPARTMENT PERFORMANCE REPORT');
    csvRows.push('');

    // Report Metadata
    csvRows.push('Report Details');
    csvRows.push('─'.repeat(120));
    csvRows.push(`Report ID,RPT-${Date.now()}`);
    csvRows.push(`Generated Date,${exportDate}`);
    csvRows.push(`Generated By,${options.generatedBy}`);
    csvRows.push(`Report Period,${periodLabel}`);
    csvRows.push(`Department,${options.department === 'all' ? 'All Departments' : options.department}`);
    csvRows.push(`Total Records,${departments.length}`);
    csvRows.push('');

    // Column Headers
    csvRows.push('Department Performance Data');
    csvRows.push('─'.repeat(120));
    csvRows.push(
      'Department,Total Employees,Avg Attendance %,Avg Productivity %,Performance Score %,Tasks Completed,Tasks Pending,Status'
    );

    // Data Rows
    if (departments.length === 0) {
      csvRows.push('No department records found for the selected period');
    } else {
      departments.forEach((dept) => {
        const row = [
          dept.name || '',
          dept.totalEmployees || 0,
          dept.avgAttendance || 0,
          dept.avgProductivity || 0,
          dept.performanceScore || 0,
          dept.tasksCompleted || 0,
          dept.tasksPending || 0,
          dept.status || 'average',
        ];
        csvRows.push(row.join(','));
      });
    }

    csvRows.push('');

    // Summary Statistics
    if (departments.length > 0) {
      csvRows.push('Summary Statistics');
      csvRows.push('─'.repeat(120));
      csvRows.push(`Total Departments,${departments.length}`);
      csvRows.push(
        `Average Attendance,${Math.round(departments.reduce((sum, d) => sum + d.avgAttendance, 0) / departments.length)}%`
      );
      csvRows.push(
        `Average Productivity,${Math.round(departments.reduce((sum, d) => sum + d.avgProductivity, 0) / departments.length)}%`
      );
      csvRows.push(
        `Average Performance Score,${Math.round(departments.reduce((sum, d) => sum + d.performanceScore, 0) / departments.length)}%`
      );
    }

    csvRows.push('');
    csvRows.push(...generateFooterWithDetails());

    const csvContent = csvRows.join('\n');
    const fileName = `Department_Report_${options.department}_${new Date().toISOString().split('T')[0]}.csv`;
    const fileUri = (FileSystem as any).documentDirectory + fileName;

    await (FileSystem as any).writeAsStringAsync(fileUri, csvContent, {
      encoding: (FileSystem as any).EncodingType?.UTF8,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/csv',
        dialogTitle: 'Save Department Performance Report',
        UTI: 'public.comma-separated-values-text',
      });
    } else {
      Alert.alert('Success', `Report saved to: ${fileUri}`);
    }
  } catch (error: any) {
    console.error('CSV Export Failed:', error);
    throw new Error(error.message || 'Failed to export department report');
  }
};

// PDF Export for Departments (Text-based)
export const generateDepartmentPDF = async (
  departments: DepartmentData[],
  options: ExportOptions
): Promise<void> => {
  try {
    const reportLines: string[] = [];
    const periodLabel = getPeriodLabel(options);
    const exportDate = formatDateIST(new Date());

    // Header
    reportLines.push(...generateHeader());
    reportLines.push('');

    // Report Title
    reportLines.push('DEPARTMENT PERFORMANCE REPORT'.padStart(65).padEnd(120));
    reportLines.push('');

    // Report Metadata
    reportLines.push('Report Details');
    reportLines.push('─'.repeat(120));
    reportLines.push(`Report ID: RPT-${Date.now()}`.padEnd(120));
    reportLines.push(`Generated Date: ${exportDate}`.padEnd(120));
    reportLines.push(`Generated By: ${options.generatedBy}`.padEnd(120));
    reportLines.push(`Report Period: ${periodLabel}`.padEnd(120));
    reportLines.push(`Department: ${options.department === 'all' ? 'All Departments' : options.department}`.padEnd(120));
    reportLines.push(`Total Records: ${departments.length}`.padEnd(120));
    reportLines.push('');

    // Table Header
    reportLines.push('Department Performance Data');
    reportLines.push('─'.repeat(120));
    reportLines.push(
      '| Department          | Employees | Att | Prod | Score | Completed | Pending | Status    |'
    );
    reportLines.push('├' + '─'.repeat(118) + '┤');

    // Table Data
    if (departments.length === 0) {
      reportLines.push('| No department records found for the selected period'.padEnd(119) + '|');
    } else {
      departments.forEach((dept) => {
        const deptName = (dept.name || '').substring(0, 19).padEnd(19);
        const employees = String(dept.totalEmployees || 0).padStart(9);
        const att = String(dept.avgAttendance || 0).padStart(3);
        const prod = String(dept.avgProductivity || 0).padStart(4);
        const score = String(dept.performanceScore || 0).padStart(5);
        const completed = String(dept.tasksCompleted || 0).padStart(9);
        const pending = String(dept.tasksPending || 0).padStart(7);
        const status = (dept.status || 'avg').substring(0, 9).padEnd(9);

        reportLines.push(
          `| ${deptName} | ${employees} | ${att}% | ${prod}% | ${score}% | ${completed} | ${pending} | ${status} |`
        );
      });
    }

    reportLines.push('└' + '─'.repeat(118) + '┘');
    reportLines.push('');

    // Summary Statistics
    if (departments.length > 0) {
      reportLines.push('Summary Statistics');
      reportLines.push('─'.repeat(120));
      const avgAttendance = Math.round(departments.reduce((sum, d) => sum + d.avgAttendance, 0) / departments.length);
      const avgProductivity = Math.round(departments.reduce((sum, d) => sum + d.avgProductivity, 0) / departments.length);
      const avgScore = Math.round(departments.reduce((sum, d) => sum + d.performanceScore, 0) / departments.length);

      reportLines.push(`Total Departments Analyzed: ${departments.length}`.padEnd(120));
      reportLines.push(`Average Attendance: ${avgAttendance}%`.padEnd(120));
      reportLines.push(`Average Productivity: ${avgProductivity}%`.padEnd(120));
      reportLines.push(`Average Performance Score: ${avgScore}%`.padEnd(120));
    }

    reportLines.push('');
    reportLines.push(...generateFooterWithDetails());

    const textContent = reportLines.join('\n');
    const fileName = `Department_Report_${options.department}_${new Date().toISOString().split('T')[0]}.txt`;
    const fileUri = (FileSystem as any).documentDirectory + fileName;

    await (FileSystem as any).writeAsStringAsync(fileUri, textContent, {
      encoding: (FileSystem as any).EncodingType?.UTF8,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: 'Save Department Performance Report',
        UTI: 'public.plain-text',
      });
    } else {
      Alert.alert('Success', `Report saved to: ${fileUri}`);
    }
  } catch (error: any) {
    console.error('PDF Export Failed:', error);
    throw new Error(error.message || 'Failed to export department report');
  }
};
